#!/bin/sh
#make -C /usr/ports/databases/mysql80-server clean reinstall

#make -C /usr/ports/www/nginx clean reinstall

rm /usr/local/etc/php/*.ini



PHPPORT=$1
 if ( test "$1" = "" ) then
 #PHPPORT=php56
 PHPPORT=php70
 MYSQLSRV=mysql80-server

 fi
LINE=`whereis -s $PHPPORT | awk '{print $2}' | cut -c 12-127`
echo $LINE
LINE1=`whereis -s $MYSQLSRV | awk '{print $2}' | cut -c 12-127`
echo $LINE1

L1=`whereis -s  $PHPPORT-calendar | awk '{print $2}' | cut -c 12-127`
L2=`whereis -s  $PHPPORT-ctype | awk '{print $2}' | cut -c 12-127`
L3=`whereis -s  $PHPPORT-curl | awk '{print $2}' | cut -c 12-127`
L4=`whereis -s  $PHPPORT-dba | awk '{print $2}' | cut -c 12-127` 
L5=`whereis -s  $PHPPORT-dom | awk '{print $2}' | cut -c 12-127` 
L6=`whereis -s  $PHPPORT-exif | awk '{print $2}' | cut -c 12-127`
L7=`whereis -s  $PHPPORT-ftp | awk '{print $2}' | cut -c 12-127`
L8=`whereis -s  $PHPPORT-fileinfo | awk '{print $2}' | cut -c 12-127`
L9=`whereis -s  $PHPPORT-filter | awk '{print $2}' | cut -c 12-127`
L10=`whereis -s  $PHPPORT-gd | awk '{print $2}' | cut -c 12-127`
L11=`whereis -s  $PHPPORT-gettext | awk '{print $2}' | cut -c 12-127`
L12=`whereis -s  $PHPPORT-hash | awk '{print $2}' | cut -c 12-127`
L13=`whereis -s  $PHPPORT-iconv | awk '{print $2}' | cut -c 12-127`
L14=`whereis -s  $PHPPORT-imap | awk '{print $2}' | cut -c 12-127`
L15=`whereis -s  $PHPPORT-json | awk '{print $2}' | cut -c 12-127`
L16=`whereis -s  $PHPPORT-mbstring | awk '{print $2}' | cut -c 12-127`
L17=`whereis -s  $PHPPORT-mcrypt | awk '{print $2}' | cut -c 12-127`
L18=`whereis -s  $PHPPORT-mysql | awk '{print $2}' | cut -c 12-127`
L19=`whereis -s  $PHPPORT-mysqli | awk '{print $2}' | cut -c 12-127`
#test 4 core dump
L20=`whereis -s  $PHPPORT-opcache | awk '{print $2}' | cut -c 12-127`
L21=`whereis -s  $PHPPORT-bz2 | awk '{print $2}' | cut -c 12-127`
L22=`whereis -s  $PHPPORT-openssl | awk '{print $2}' | cut -c 12-127`
L23=`whereis -s  $PHPPORT-pcntl | awk '{print $2}' | cut -c 12-127`
#?
L24=`whereis -s  $PHPPORT-pdo | awk '{print $2}' | cut -c 12-127`
L25=`whereis -s  $PHPPORT-pdo_mysql | awk '{print $2}' | cut -c 12-127`
L26=`whereis -s  $PHPPORT-pdo_sqlite | awk '{print $2}' | cut -c 12-127`
L27=`whereis -s  $PHPPORT-phar | awk '{print $2}' | cut -c 12-127`
L28=`whereis -s  $PHPPORT-posix | awk '{print $2}' | cut -c 12-127`
# make -C `whereis -s  $PHPPORT-recode | awk '{print $2}' | cut -c 12-127` reinstall

L29=`whereis -s  $PHPPORT-session | awk '{print $2}' | cut -c 12-127`
L30=`whereis -s  $PHPPORT-simplexml | awk '{print $2}' | cut -c 12-127`
L31=`whereis -s  $PHPPORT-snmp | awk '{print $2}' | cut -c 12-127`
L32=`whereis -s  $PHPPORT-socket | awk '{print $2}' | cut -c 12-127`
L33=`whereis -s  $PHPPORT-sqlite3 | awk '{print $2}' | cut -c 12-127`
L34=`whereis -s  $PHPPORT-tokenizer | awk '{print $2}' | cut -c 12-127`
L35=`whereis -s  $PHPPORT-xml | awk '{print $2}' | cut -c 12-127`
L36=`whereis -s  $PHPPORT-xmlreader | awk '{print $2}' | cut -c 12-127`
L37=`whereis -s  $PHPPORT-xmlwriter | awk '{print $2}' | cut -c 12-127`
L38=`whereis -s  $PHPPORT-xsl | awk '{print $2}' | cut -c 12-127`
L39=`whereis -s  $PHPPORT-zip | awk '{print $2}' | cut -c 12-127`
L40=`whereis -s  $PHPPORT-zlib | awk '{print $2}' | cut -c 12-127`

LIN="$LINE ${LINE1} ${L1} ${L2} ${L3} ${L4} ${L5} ${L6} ${L7} $L8 $L9 $L10 $L11 $L12 $L13 $L14 $L15 $L16 $L17 $L18 $L19 $L20 $L21 $L22 $L23 $L24 $L25 $L26 $L27 $L28 $L29 $L30 $L31 $L32 $L33 $L34 $L35 $L36 $L37 $L38 $L39 $L40"
echo $LINE
echo $LIN


pkg query %o | grep php | awk '{print $1}'  >> php-ports
echo $LIN > php-p
#cat php-ports |xargs pkg delete -y
pkg install -fy $LIN

#pkg install $LIN



#make -C $LINE clean reinstall
#LINST=`whereis -s $LINE | awk '{print $2}'| cut -c 1-8`

make -C `whereis -s phpMyAdmin | awk '{print $2}'` deinstall install
make -C `whereis -s pecl-imagick | awk '{print $2}'` deinstall install
make -C /usr/local/www/wordpress deinstall install

#make -C `whereis -s  $PHPPORT-calendar | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-ctype | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-curl | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-dba | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-dom | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-exif | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-ftp | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-fileinfo | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-filter | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-gd | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-gettext | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-hash | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-iconv | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-imap | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-json | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-mbstring | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-mcrypt | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-mysql | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-mysqli | awk '{print $2}'` reinstall
#test 4 core dump
#make -C `whereis -s  $PHPPORT-opcache | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-bz2 | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-openssl | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-pcntl | awk '{print $2}'` reinstall
#?
#make -C `whereis -s  $PHPPORT-pdo | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-pdo_mysql | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-pdo_sqlite | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-phar | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-posix | awk '{print $2}'` reinstall
## make -C `whereis -s  $PHPPORT-recode | awk '{print $2}'` reinstall

#make -C `whereis -s  $PHPPORT-session | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-simplexml | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-snmp | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-socket | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-sqlite3 | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-tokenizer | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-xml | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-xmlreader | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-xmlwriter | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-xsl | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-zip | awk '{print $2}'` reinstall
#make -C `whereis -s  $PHPPORT-zlib | awk '{print $2}'` reinstall

#make -C `whereis -s  $PHPPORT| awk '{print $2}'` clean
service mysql-server restart
wait 15
service mysql-server status
service mysql-server start
service php-fpm restart
service nginx restart


#pkg query %ro | grep php | xargs portmaster
