#!/bin/sh
## php gluk gluk fight with restart php-fpm toomany bugs
#
 #pkgng pack create packages for freebsd port and all dependency
 # virtualbox and vlc mplayer libav mesa -all new and not from ports up to date
#/usr/update-svn
#n=4
cd /root
# minimal set for //no apache //nginx wp phpMyAdmin bitrix drupal ImageMagick
PHPPORT="php72"
LINETX="`whereis -s $PHPPORT  | awk '{print $2}' |cut -c 12-127`"
PACKAGELINE="$LINETX ftp/$PHPPORT-curl graphics/$PHPPORT-gd devel/$PHPPORT-gettext textproc/$PHPPORT-xml archivers/$PHPPORT-zip converters/$PHPPORT-mbstring www/$PHPPORT-session textproc/$PHPPORT-xml devel/$PHPPORT-tokenizer security/$PHPPORT-hash archivers/$PHPPORT-bz2 textproc/$PHPPORT-ctype security/$PHPPORT-filter archivers/$PHPPORT-zip security/$PHPPORT-openssl devel/$PHPPORT-gettext graphics/$PHPPORT-gd ftp/$PHPPORT-ftp databases/$PHPPORT-mysqli devel/$PHPPORT-json archivers/$PHPPORT-zlib databases/phpmyadmin graphics/pecl-imagick re2c p5-Locale-Gettext pcre ncurses rust nspr nginx net-snmp iconv libiconv $PHPPORT-iconv gettext-tools gdbm cclient "
printf "$PACKAGELINE" >>listpkg
#clean list (list w/o repeating names)
printf "databases/phpmyadmin " >listpkge
#printf "\n" >>
##pear-HTTP_Session2  ??
#clear too
printf "security/$PHPPORT-mcrypt\n" >listbld
printf "databases/pear-DB\n" >>listbld
pkg query %ro | grep php > listpkg
pkg query %ro | grep p5- >> listpkg
pkg query %ro | grep pear >> listpkg
# remove repeat lines
 for ARG in `cat listpkg`
 do
  if (test "" == "`cat /root/listpkg |grep $ARG`")  then
      if (test "$ARG" != "databases/phpmyadmin")  then
      if (test "$ARG" != "security/php72-mcrypt")  then
    # list packages to build - not in pkg or another names  
        if (test "" == "`cat /root/listbld |grep $ARG`")  then

         PACKAGELINE="$PACKAGELINE ${ARG}"
        fi
      fi
      fi
#        # arithmetic increment use expr command freebsd ubuntu (spaces req.)
#        n=`expr $n + 1`
  fi
 done
printf "$PACKAGELINE" >> listpkge


rm /root/reins-port.log
#number of arguments in command line (parse all- not use) #count # of packages
#n=$#
n=1

printf "$PACKAGELINE" > packages-input
#PACKAGELINE=$ARG
#echo $PACKAGELINE
## reinstall
# comment 4 test
 pkg delete -fy $PACKAGELINE
 pkg install -y $PACKAGELINE

# ..using sat solver ..works no  need to build from source freebsd 12.1
exit 0

# --- big cycle
#for ARG in $*
for ARG in `cat listpkge`
 do
 echo $ARG
 echo $n
PORTPATH=`whereis -s $ARG | awk '{print $2}'`
#echo $PORTPATH
#
 if (test "$ARG" != "databases/phpmyadmin")  then 
 PACKAGELINE=$ARG
 fi
#increment all dependency
printf "$PACKAGELINE \n \n" >>packages-php-cycle
printf "ports-mgmt/pkg" >> /root/reins-port.log
printf "\n" >> /root/reins-port.log
# -- middle cycle -all dep's for each package
   for LINE in `make -C $PORTPATH all-depends-list |cut -c 12-127`
     do
     LINST=`whereis -s $LINE | awk '{print $2}'| cut -c 1-8`
         if (test "$LINE" != "ports-mgmt/pkg")  then
          if (test "$LINST" != "/usr/src")  then
	    if (test "" == "`cat /root/reins-port.log |grep $LINE`")  then
        echo -n "build  (${LINE}) "
	PORTP=`whereis -s $LINE | awk '{print $2}'`
	echo -n " from ($PORTP) "
        PACKAGELINE="$PACKAGELINE ${LINE}"
        # arithmetic increment use expr command freebsd ubuntu (spaces req.)
        n=`expr $n + 1`
        printf "$PORTPATH  \n ------------------------- \n \n" >> /root/reins-port.log
        printf  "${LINE}\n" >> /root/reins-port.log
      # printf "`cat /root/reins-port.log |grep $LINE`\n" >> /root/reins-port1-log
        #echo "\n" >> /root/reins-log
         if (test "$LINE" == "devel/gettext-runtime")  then
          pkg delete -fy gettext-runtime
          pkg install -y gettext-runtime
         break
        #make -C /usr/ports/${LINE} build deinstall install | tail >>~/reins.texi
         fi
        #make -C /usr/ports/${LINE} reinstall | tail >>~/reins.texi
    #make -C /usr/ports/${LINE} clean
## reinstall
# comment 4 test
  #pkg delete -fy $LINE
 #	echo -n "($LINE)"
  #pkg install -y $LINE
	#make -C /usr/ports/ports-mgmt/pkg install
	    else #echo -n "ist schon bearbeitet ($LINE) "
	    fi
          else #printf "\n system package  $LINE  try cd /usr/src make buildworld \n" >> /root/reins-port.log
          fi
         fi
     done
     echo -n $n
# -- middle cycle end
 # if $$i == "" then break  fi
 # if $$i > $n then break fi
 done
# --- big cycle end
#pkg install -y $PACKAGELINE
#pkg check -d
#echo $PACKAGELINE
printf "$PACKAGELINE" >> do-reins-php

#make -C /usr/ports/${LINE} clean
#PACKAGELINE ="'cat listpkge'"
PACKAGELINE=$PACKAGELINE phpmyadmin-$PHPPORT

pkg install -y $PACKAGELINE
 PACKAGELINE="$PACKAGELINE databases/phpmyadmin"

make -C `whereis -s pecl-imagick | awk '{print $2}'` clean reinstall clean
make -C /usr/ports/databases/mysql57-server clean reinstall clean
#make -C /usr/ports/databases/phpmyadmin clean reinstall clean #new phpmyadmin-php72
#filter & ext
#nginx freebsd re-compile all +modules
make -C /usr/ports/www/wordpress clean reinstall clean
make -C /usr/ports/miltimedia/vlc clean reinstall clean
make -C /usr/ports/multimedia/ffmpeg  clean reinstall clean
make -C /usr/ports/www/nginx clean reinstall clean
pkg install -y firefox
pkg install -y chrome
service php-fpm restart
service nginx restart
service mysql-server restart
