#!/usr/local/bin/bash
# install orbit gdm gnome3 base64 net/vino
gconftool-2 -s -t bool /desktop/gnome/remote_access/enabled true
gconftool-2 -s -t bool /desktop/gnome/remote_access/require-encryption false
gconftool-2 -s -t bool /desktop/gnome/remote_access/require_encryption false
gconftool-2 -s -t bool /desktop/gnome/remote_access/prompt-enabled false
gconftool-2 -s -t bool /desktop/gnome/remote_access/prompt_enabled false
gconftool-2 -s -t list --list-type=string  /desktop/gnome/remote_access/authentication_methods '[vnc]'
#gconftool-2 --set /desktop/gnome/remote_access/authentication_methods --type list --list-type string '[vnc]'
gconftool-2 --set /desktop/gnome/remote_access/vnc_passwd --type string `echo -n 'nv1050' | base64`
gsettings set org.gnome.Vino require-encryption false
killall vino-server
killall x11vnc
gnome-terminal -- /usr/local/libexec/vino-server --display=:0
ps -ax | grep vino
